In [43]:
import numpy as np
from multicam.qt import qt, qt_gauss, qt_gauss_base, qt_inverse_gauss_base
from numpy import ndarray
from scipy.stats import rankdata
from sklearn import linear_model


from multicam_tng.multicam2 import _get_ranks_based, _create_rank_lookup

In [44]:
x = np.array([2, 6, 8, 10, 4, 4, 4, 12, 16]).reshape(-1, 1)
x1 = np.array([1, 3, 4, 4.5, 12]).reshape(-1, 1)

In [45]:
xg = qt_gauss(x)
xg

array([[-1.28155157],
       [ 0.        ],
       [ 0.2533471 ],
       [ 0.52440051],
       [-0.84162123],
       [-0.52440051],
       [-0.2533471 ],
       [ 0.84162123],
       [ 1.28155157]])

In [39]:
lookup = _create_rank_lookup(x)


In [41]:
xr1 = _get_ranks_based(x1, x, lookup)
xr1

array([[1.  ],
       [1.5 ],
       [3.  ],
       [4.25],
       [8.  ]])

In [42]:
xrt = rankdata(x, axis=0, method="ordinal")
xg1 = qt_gauss_base(xr1, xrt)
xg1

array([[-1.28155157],
       [-1.0615864 ],
       [-0.52440051],
       [-0.19001033],
       [ 0.84162123]])